---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

#branches:
#  only:
#    - main
# If we decide to build on all branches, remove this section completely.
# For now, removed to enable building on other branches + fixing the name of branch to 'main'

script:
  - npm test
